baseURL = "/"
languageCode = "en-us"
title = "This Is My Cloud Portal"
theme = "sam"

[params]
    #dateform             = "Mon Jan 02, 2006"
    #dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    #favicon              = "sam.ico"
    homepage             = "portal"
    footerText           = "Works like a portal."

[[params.mainMenu]]
    link = "https://status.thisismy.cloud"
    text = "status"

[[params.mainMenu]]
    link = "https://backups.thisismy.cloud"
    text = "backups"

[[params.mainMenu]]
    link = "https://sync.thisismy.cloud"
    text = "cloud"

[[params.mainMenu]]
    link = "https://dns.thisismy.cloud"
    text = "dns"

[[params.mainMenu]]
    link = "https://gamepanel.thisismy.cloud"
    text = "game panel"

[[params.mainMenu]]
    link = "https://mail.thisismy.cloud"
    text = "mail"

[[params.mainMenu]]
    link = "https://manage.thisismy.cloud"
    text = "management"

[[params.mainMenu]]
    link = "https://proxy.thisismy.cloud"
    text = "proxy"

[[params.mainMenu]]
    link = "/teamspeak3"
    text = "teamspeak 3"

[[params.mainMenu]]
    link = "/servers"
    text = "servers"

[[params.mainMenu]]
    link = "/about"
    text = "what is this?"