baseURL = "/"
languageCode = "en-us"
title = "This Is My Cloud Portal"
theme = "sam"

[params]
    #dateform             = "Mon Jan 02, 2006"
    #dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "favicon.ico"
    homepage             = "portal"
    footerText           = "Works like a portal."

[[params.mainMenu]]
    link = "https://status.thisismy.cloud"
    text = "status"

[[params.mainMenu]]
    link = "https://dns.thisismy.cloud"
    text = "dns"

[[params.mainMenu]]
    link = "https://gamepanel.thisismy.cloud"
    text = "game panel"

[[params.mainMenu]]
    link = "https://mail.thisismy.cloud"
    text = "mail"

[[params.mainMenu]]
    link = "https://vault.thisismy.cloud"
    text = "vault"

[[params.mainMenu]]
    link = "https://board.thisismy.cloud"
    text = "board"

[[params.mainMenu]]
    link = "/teamspeak3"
    text = "teamspeak 3"

[[params.mainMenu]]
    link = "/about"
    text = "what is this?"