baseURL = "/"
languageCode = "en-us"
title = "This Is My Cloud Portal"
theme = "sam"

[params]
    #dateform             = "Mon Jan 02, 2006"
    #dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    #favicon              = "sam.ico"
    homepage             = "portal"
    footerText           = "Works like a portal."

[[params.mainMenu]]
    link = "https://box.thisismy.cloud/admin"
    text = "mail-in-a-box"

[[params.mainMenu]]
    link = "https://box.thisismy.cloud/mail"
    text = "roundcube"

[[params.mainMenu]]
    link = "https://box.thisismy.cloud/cloud"
    text = "nextcloud"

[[params.mainMenu]]
    link = "https://gamepanel.thisismy.cloud"
    text = "pterodactyl"

[[params.mainMenu]]
    link = "https://pihole.thisismy.cloud/admin"
    text = "pi-hole"

[[params.mainMenu]]
    link = "/teamspeak3"
    text = "teamspeak 3"

[[params.mainMenu]]
    link = "/servers"
    text = "servers"

[[params.mainMenu]]
    link = "/about"
    text = "about"